// <auto-generated />
using System;
using IstasyonDemo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IstasyonDemo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222125832_AddPusulaTable")]
    partial class AddPusulaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IstasyonDemo.Api.Models.FiloSatis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FiloKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FisNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Litre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PompaNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<int>("YakitTuru")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId");

                    b.ToTable("FiloSatislar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomasyonSatis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FisNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Litre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonelKeyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Plaka")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PompaNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<int>("YakitTuru")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("OtomasyonSatislar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OtomasyonAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Pusula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PusulaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Turu")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId");

                    b.ToTable("Pusulalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DosyaAdi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("DosyaIcerik")
                        .HasColumnType("bytea");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarketToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PompaToplam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.FiloSatis", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("FiloSatislar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomasyonSatis", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("OtomasyonSatislar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Pusula", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("Pusulalar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Vardiya", b =>
                {
                    b.Navigation("FiloSatislar");

                    b.Navigation("OtomasyonSatislar");

                    b.Navigation("Pusulalar");
                });
#pragma warning restore 612, 618
        }
    }
}
