// <auto-generated />
using System;
using IstasyonDemo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IstasyonDemo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103191957_AddSilinemezToPusulaDigerOdeme")]
    partial class AddSilinemezToPusulaDigerOdeme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IstasyonDemo.Api.Models.AylikStokOzeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ay")
                        .HasColumnType("integer");

                    b.Property<decimal>("AyGiris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AySatis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DevirStok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HesaplamaZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KalanStok")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Kilitli")
                        .HasColumnType("boolean");

                    b.Property<int>("YakitId")
                        .HasColumnType("integer");

                    b.Property<int>("Yil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YakitId", "Yil", "Ay")
                        .IsUnique()
                        .HasDatabaseName("IX_AylikStokOzeti_YakitYilAy");

                    b.ToTable("AylikStokOzetleri");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.DosyaYuklemeAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("DosyaUzantisi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HedefTablo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<string>("XmlNodeMappingJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId");

                    b.ToTable("DosyaYuklemeAyarlari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.FaturaStokTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GirenMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KalanMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("boolean");

                    b.Property<int>("YakitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YakitId", "FaturaTarihi")
                        .HasDatabaseName("IX_FaturaStokTakip_YakitFaturaTarihi");

                    b.ToTable("FaturaStokTakipleri");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.FiloSatis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FiloKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FisNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Litre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PompaNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId")
                        .HasDatabaseName("IX_FiloSatislar_VardiyaId");

                    b.ToTable("FiloSatislar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("PatronId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatronId");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Istasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("integer");

                    b.Property<string>("IstasyonKodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("IstasyonSorumluId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastConnectionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MarketSorumluId")
                        .HasColumnType("integer");

                    b.Property<string>("OtomasyonFiloKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OtomatikDosyaYolu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RegisteredDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("VardiyaSorumluId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("IstasyonSorumluId");

                    b.HasIndex("MarketSorumluId");

                    b.HasIndex("VardiyaSorumluId");

                    b.ToTable("Istasyonlar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.IstasyonAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountDecimal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDecimal")
                        .HasColumnType("integer");

                    b.Property<int>("UnitPriceDecimal")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId");

                    b.ToTable("IstasyonAyarlari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketGelir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BelgeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GelirTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MarketVardiyaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketVardiyaId");

                    b.ToTable("MarketGelirler");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketGider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BelgeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GiderTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MarketVardiyaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketVardiyaId");

                    b.ToTable("MarketGiderler");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketTahsilat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("KrediKarti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MarketVardiyaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Nakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ParoPuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SistemSatisTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Toplam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarketVardiyaId");

                    b.HasIndex("PersonelId");

                    b.ToTable("MarketTahsilatlar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketVardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SorumluId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamFark")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToplamSatisTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToplamTeslimatTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ZRaporuNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ZRaporuTutari")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId")
                        .HasDatabaseName("IX_MarketVardiyalar_IstasyonId");

                    b.HasIndex("SorumluId");

                    b.HasIndex("Tarih")
                        .IsDescending()
                        .HasDatabaseName("IX_MarketVardiyalar_Tarih");

                    b.ToTable("MarketVardiyalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketZRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kdv0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kdv1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kdv10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kdv20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvHaricToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MarketVardiyaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketVardiyaId");

                    b.ToTable("MarketZRaporlari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RelatedLogId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedMarketVardiyaId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedVardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IX_Notifications_IsRead");

                    b.HasIndex("RelatedMarketVardiyaId");

                    b.HasIndex("RelatedVardiyaId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomasyonSatis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FisNo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Litre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonelKeyId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Plaka")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PompaNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId")
                        .HasDatabaseName("IX_OtomasyonSatislar_PersonelId");

                    b.HasIndex("VardiyaId")
                        .HasDatabaseName("IX_OtomasyonSatislar_VardiyaId");

                    b.ToTable("OtomasyonSatislar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomatikDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("DosyaIcerigi")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HataMesaji")
                        .HasColumnType("text");

                    b.Property<bool>("Islendi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IslenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId");

                    b.ToTable("OtomatikDosyalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("EskiKeyId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KeyGuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("KeyOlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtomasyonAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId")
                        .HasDatabaseName("IX_Personeller_IstasyonId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PompaGider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("BelgeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GiderTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId");

                    b.ToTable("PompaGiderler");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Pusula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("KrediKarti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KrediKartiDetay")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Nakit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("PusulaTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId")
                        .HasDatabaseName("IX_Pusulalar_PersonelId");

                    b.HasIndex("VardiyaId")
                        .HasDatabaseName("IX_Pusulalar_VardiyaId");

                    b.ToTable("Pusulalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PusulaDigerOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PusulaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Silinemez")
                        .HasColumnType("boolean");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TurKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PusulaId");

                    b.ToTable("PusulaDigerOdemeleri");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PusulaKrediKartiDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PusulaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PusulaId");

                    b.ToTable("PusulaKrediKartiDetaylari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.SystemDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SystemDefinitions");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.TankGiris", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GelisYontemi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kaydeden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Litre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UrunGirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YakitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Tarih")
                        .IsDescending()
                        .HasDatabaseName("IX_TankGirisler_Tarih");

                    b.HasIndex("YakitId");

                    b.ToTable("TankGirisler");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<string>("FotografData")
                        .HasColumnType("text");

                    b.Property<int?>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("ExtraSettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Vardiya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DosyaAdi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DosyaHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("DosyaIcerik")
                        .HasColumnType("bytea");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fark")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarketToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnaylayanAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OnaylayanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PompaToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SilinmeTalebiNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SilinmeTalebiOlusturanAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SilinmeTalebiOlusturanId")
                        .HasColumnType("integer");

                    b.Property<string>("SorumluAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SorumluId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaslangicTarihi")
                        .IsDescending()
                        .HasDatabaseName("IX_Vardiyalar_BaslangicTarihi");

                    b.HasIndex("Durum")
                        .HasDatabaseName("IX_Vardiyalar_Durum");

                    b.HasIndex("IstasyonId");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EskiDurum")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciRol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("YeniDurum")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IslemTarihi")
                        .IsDescending()
                        .HasDatabaseName("IX_VardiyaLoglari_IslemTarihi");

                    b.HasIndex("VardiyaId")
                        .HasDatabaseName("IX_VardiyaLoglari_VardiyaId");

                    b.ToTable("VardiyaLoglari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaTankEnvanteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaslangicStok")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BeklenenTuketim")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BitisStok")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FarkMiktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SatilanMiktar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SevkiyatMiktar")
                        .HasColumnType("numeric");

                    b.Property<string>("TankAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TankNo")
                        .HasColumnType("integer");

                    b.Property<int>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("YakitTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VardiyaId");

                    b.ToTable("VardiyaTankEnvanterleri");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaXmlLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IstasyonId")
                        .HasColumnType("integer");

                    b.Property<string>("PumpDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("SaleDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("TankDetailsJson")
                        .HasColumnType("text");

                    b.Property<int?>("VardiyaId")
                        .HasColumnType("integer");

                    b.Property<string>("XmlIcerik")
                        .HasColumnType("text");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ZipDosyasi")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("IstasyonId");

                    b.HasIndex("VardiyaId");

                    b.ToTable("VardiyaXmlLoglari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Yakit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OtomasyonUrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Yakitlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Motorin",
                            OtomasyonUrunAdi = "MOTORIN,DIZEL",
                            Renk = "#F59E0B",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Benzin (Kurşunsuz 95)",
                            OtomasyonUrunAdi = "BENZIN,KURŞUNSUZ,KURSUNSUZ",
                            Renk = "#EF4444",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Ad = "LPG",
                            OtomasyonUrunAdi = "LPG,OTOGAZ",
                            Renk = "#3B82F6",
                            Sira = 3
                        });
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.AylikStokOzeti", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Yakit", "Yakit")
                        .WithMany()
                        .HasForeignKey("YakitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yakit");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.DosyaYuklemeAyarlari", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId");

                    b.Navigation("Istasyon");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.FaturaStokTakip", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Yakit", "Yakit")
                        .WithMany()
                        .HasForeignKey("YakitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yakit");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.FiloSatis", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("FiloSatislar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Firma", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.User", "Patron")
                        .WithMany()
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patron");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Istasyon", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Firma", "Firma")
                        .WithMany("Istasyonlar")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IstasyonDemo.Api.Models.User", "IstasyonSorumlu")
                        .WithMany()
                        .HasForeignKey("IstasyonSorumluId");

                    b.HasOne("IstasyonDemo.Api.Models.User", "MarketSorumlu")
                        .WithMany()
                        .HasForeignKey("MarketSorumluId");

                    b.HasOne("IstasyonDemo.Api.Models.User", "VardiyaSorumlu")
                        .WithMany()
                        .HasForeignKey("VardiyaSorumluId");

                    b.Navigation("Firma");

                    b.Navigation("IstasyonSorumlu");

                    b.Navigation("MarketSorumlu");

                    b.Navigation("VardiyaSorumlu");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.IstasyonAyarlari", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Istasyon");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketGelir", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.MarketVardiya", "MarketVardiya")
                        .WithMany("Gelirler")
                        .HasForeignKey("MarketVardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketVardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketGider", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.MarketVardiya", "MarketVardiya")
                        .WithMany("Giderler")
                        .HasForeignKey("MarketVardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketVardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketTahsilat", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.MarketVardiya", "MarketVardiya")
                        .WithMany("Tahsilatlar")
                        .HasForeignKey("MarketVardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IstasyonDemo.Api.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarketVardiya");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketVardiya", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IstasyonDemo.Api.Models.User", "Sorumlu")
                        .WithMany()
                        .HasForeignKey("SorumluId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Istasyon");

                    b.Navigation("Sorumlu");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketZRaporu", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.MarketVardiya", "MarketVardiya")
                        .WithMany("ZRaporlari")
                        .HasForeignKey("MarketVardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketVardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Notification", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.MarketVardiya", "RelatedMarketVardiya")
                        .WithMany()
                        .HasForeignKey("RelatedMarketVardiyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "RelatedVardiya")
                        .WithMany()
                        .HasForeignKey("RelatedVardiyaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IstasyonDemo.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedMarketVardiya");

                    b.Navigation("RelatedVardiya");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomasyonSatis", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId");

                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("OtomasyonSatislar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.OtomatikDosya", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Istasyon");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Personel", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany("Calisanlar")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Istasyon");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PompaGider", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("Giderler")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Pusula", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany("Pusulalar")
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PusulaDigerOdeme", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Pusula", "Pusula")
                        .WithMany("DigerOdemeler")
                        .HasForeignKey("PusulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pusula");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.PusulaKrediKartiDetay", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Pusula", "Pusula")
                        .WithMany("KrediKartiDetaylari")
                        .HasForeignKey("PusulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pusula");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.RolePermission", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.TankGiris", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Yakit", "Yakit")
                        .WithMany()
                        .HasForeignKey("YakitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Yakit");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.User", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IstasyonDemo.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Istasyon");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.UserSettings", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("IstasyonDemo.Api.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Vardiya", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany("Vardiyalar")
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Istasyon");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaLog", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaTankEnvanteri", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("VardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.VardiyaXmlLog", b =>
                {
                    b.HasOne("IstasyonDemo.Api.Models.Istasyon", "Istasyon")
                        .WithMany()
                        .HasForeignKey("IstasyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IstasyonDemo.Api.Models.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("VardiyaId");

                    b.Navigation("Istasyon");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Firma", b =>
                {
                    b.Navigation("Istasyonlar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Istasyon", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Kullanicilar");

                    b.Navigation("Vardiyalar");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.MarketVardiya", b =>
                {
                    b.Navigation("Gelirler");

                    b.Navigation("Giderler");

                    b.Navigation("Tahsilatlar");

                    b.Navigation("ZRaporlari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Pusula", b =>
                {
                    b.Navigation("DigerOdemeler");

                    b.Navigation("KrediKartiDetaylari");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("IstasyonDemo.Api.Models.Vardiya", b =>
                {
                    b.Navigation("FiloSatislar");

                    b.Navigation("Giderler");

                    b.Navigation("OtomasyonSatislar");

                    b.Navigation("Pusulalar");
                });
#pragma warning restore 612, 618
        }
    }
}
